import { LocalArtifactStorage, calculateFileHash } from '@media-downloader/core';
import { processDownload, identityPool } from './engine';
import { DownloadJobData, Platform } from '@media-downloader/types';
import { Logger } from 'pino';
import fs from 'fs/promises';
import path from 'path';

const mockLogger = {
  info: () => {},
  warn: () => {},
  error: () => {},
  debug: () => {},
  child: () => mockLogger
} as unknown as Logger;

async function runTests() {
  console.log('--- Phase 10F: S3 Artifact Boundary Tests ---');

  const mockS3Dir = path.join(__dirname, '.mock-s3');
  const mockTmpDir = path.join(__dirname, '.test-tmp');

  let s3;
  try {
    s3 = new LocalArtifactStorage();
    

    // Reset S3
    await fs.rm(mockS3Dir, { recursive: true, force: true });
    await fs.mkdir(mockS3Dir, { recursive: true });
    
    await fs.rm(mockTmpDir, { recursive: true, force: true });
    await fs.mkdir(mockTmpDir, { recursive: true });
  } catch(e: any) {
    console.error('INIT ERROR:', e);
    return;
  }

  // 1. Isolated Filesystem Proof & No Leak Proof
  console.log('\nRunning Test 1: Isolated Filesystem & No Leak Proof');
  try {
    const jobData: DownloadJobData = {
      jobId: '10f-test-1',
      url: 'https://www.instagram.com/reel/isolated/',
      urlHash: 'dummy',
      platform: Platform.INSTAGRAM,
    };
    
    // Simulate Downloader placing file in ephemeral storage
    const fakeRawPath = path.join(mockTmpDir, 'job_10f-test-1', 'raw_video.mp4');
    await fs.mkdir(path.dirname(fakeRawPath), { recursive: true });
    await fs.writeFile(fakeRawPath, 'dummy-video-content');
    
    // Downloader PUTs to S3
    const artifact = await s3.putArtifact('bucket1', 'jobs/10f-test-1/raw/video.mp4', fakeRawPath);
    
    // Assert No-Leak in S3 Metadata
    if (JSON.stringify(artifact).includes('encryptedData') || JSON.stringify(artifact).includes('session')) {
       throw new Error('Credential leak detected in S3 Artifact Reference!');
    }
    
    // Delete Downloader's ephemeral filesystem (simulate container crash/isolation)
    await fs.rm(path.dirname(fakeRawPath), { recursive: true, force: true });
    
    // Processor starts in completely different directory
    const processorInput = path.join(mockTmpDir, 'processor-workspace', 'input.mp4');
    await s3.getArtifact(artifact, processorInput);
    
    const readBack = await fs.readFile(processorInput, 'utf-8');
    if (readBack !== 'dummy-video-content') {
      throw new Error('Processor failed to read correct content from S3');
    }
    console.log('✅ PASS: Worker B successfully processed data generated by Worker A after A\'s disk was destroyed.');
    console.log('✅ PASS: S3 payload is credential-free.');
  } catch (e: any) {
    console.error('❌ FAIL:', e.message);
  }

  // 2. S3/Queue Boundary Recovery Proof
  console.log('\nRunning Test 2: S3/Queue Boundary Recovery');
  try {
    const bucket = 'bucket1';
    const key = 'jobs/10f-test-2/raw/video.mp4';
    const fakeRawPath = path.join(mockTmpDir, 'job_10f-test-2', 'raw.mp4');
    
    await fs.mkdir(path.dirname(fakeRawPath), { recursive: true });
    await fs.writeFile(fakeRawPath, 'checkpoint-content');
    
    // Upload happens successfully
    const artifact1 = await s3.putArtifact(bucket, key, fakeRawPath);
    
    // CRASH happens here before Queue publish.
    
    // Retry happens. Checkpoint logic:
    const exists = await s3.artifactExists(bucket, key);
    if (!exists) throw new Error('Artifact should exist for checkpointing');
    
    const metadata = await s3.getArtifactMetadata(bucket, key);
    if (metadata.contentHash !== artifact1.contentHash) throw new Error('Integrity validation failed on checkpoint recovery');
    
    console.log('✅ PASS: Retry detected existing S3 artifact. Integrity valid. Skipped redundant download.');
  } catch (e: any) {
    console.error('❌ FAIL:', e.message);
  }

  // 3. Artifact Integrity / Concurrent Retry Proof
  console.log('\nRunning Test 3: Artifact Integrity / Concurrent Write');
  try {
    const bucket = 'bucket1';
    const key = 'jobs/10f-test-3/raw/video.mp4';
    
    const w1Path = path.join(mockTmpDir, '10f-test-3', 'w1.mp4');
    const w2Path = path.join(mockTmpDir, '10f-test-3', 'w2.mp4');
    
    await fs.mkdir(path.dirname(w1Path), { recursive: true });
    await fs.writeFile(w1Path, 'worker-1-content');
    await fs.writeFile(w2Path, 'worker-2-content');
    
    // Worker 1 uploads
    const ref1 = await s3.putArtifact(bucket, key, w1Path);
    
    // Worker 2 concurrently overwrites
    await s3.putArtifact(bucket, key, w2Path);
    
    // Processor gets payload from Worker 1, but reads from S3 which was overwritten by Worker 2
    try {
      await s3.getArtifact(ref1, path.join(mockTmpDir, '10f-test-3', 'processor.mp4'));
      throw new Error('Should have thrown an integrity error');
    } catch (e: any) {
      if (!e.message.includes('Integrity Error')) {
        throw new Error('Expected Integrity Error, got: ' + e.message);
      }
      console.log('✅ PASS: Processor rejected mismatched S3 content due to SHA-256 hash validation.');
    }
  } catch(e: any) {
     console.error('❌ FAIL:', e.message);
  }
}

runTests().then(() => process.exit(0)).catch(() => process.exit(1));
